"""Full 630-antichain verdict sweep for EIX = E_8/(E_7 x SU(2)).

Numerical support for Remark ``rem:antichain-equivariance'' in
``sections/06-emergent-spacetime.tex'': the operational verdicts of
sub-claims (alpha), (gamma), (epsilon) of Hypothesis~\\ref{hyp:4d-emergence}
are constant across the full 630-element set of maximal antichains in
Delta(m_EIX^+) (Corollary~\\ref{cor:antichain-EIX}), without invoking
analytic transitivity of the residual E_7 x SU(2) action.

Per-antichain protocol.
=======================

For each size-4 strongly-orthogonal subset
{alpha_0, ..., alpha_3} subset Delta(m^+) the script forms the abelian
flat a subset m generated by

    X_mu := E_{+alpha_mu} + E_{-alpha_mu}    (mu = 0,1,2,3),

and runs eight checks:

  C1  Strong-orthogonality of the six pairs (alpha_a, alpha_b), a < b.
  C2  Cartan involution: P_h X_mu = 0, P_m X_mu = X_mu (X_mu in m).
  C3  Pairwise commutation: max ||[X_mu, X_nu]|| < 1e-9
       (sub-claim (epsilon) of Hypothesis~\\ref{hyp:4d-emergence} on a).
  C4  Restricted Killing form: kappa|_a = 4 . 1 (positive definite on a).
  C5  Slow-mode kinetic matrix K^{mu nu} = (1/2) delta^{mu nu}
       (Eq.~\\eqref{eq:slow-mode-kinetic}; Riemannian signature on a).
  C6  Osterwalder-Schrader reflection positivity of the Yukawa kernel
       G_2(R) = (m/4 pi^2 R) K_1(m R) on N=30 random points in {tau > 0}
       (Proposition~\\ref{prop:leading-os-rp}).
  C7  O(4) gauge invariance of C6 across the four time-axis choices in a
       (E1 covariance in Proposition~\\ref{prop:gamma-global-poincare}).
  C8  Lorentzian dispersion E^2 = |k|^2 + m^2 > 0 with group velocity
       v_g < 1 on the Wick-rotated propagator (causal propagation).

Test points for C6/C7 are seeded by ``RNG_BASE_SEED + antichain_index``,
so the protocol exercises 630 x (1 + 4) = 3 150 independent OS matrices.

Expected structural outcome.
============================

The kinetic and mass coefficients K^{mu nu} = (1/||X_mu||^2) delta^{mu nu}
and M_W^2 = c_H . r_*^2 depend only on the common length |alpha_mu|^2 = 2
of long E_8 roots and on V_A in Cartan(SU(2)); both are antichain-
independent by construction, so C5--C8 are theoretically constant on
the 630-element set. Strong orthogonality forces [X_mu, X_nu] = 0 on
the Chevalley basis (Knapp 2002, Ch.~II~\\S5; cited at
Proposition~\\ref{prop:algebraic-4d}); C3 is verified numerically on
every antichain as a robustness check.

References.
===========

  - sections/06-emergent-spacetime.tex:
      Proposition~\\ref{prop:algebraic-4d},
      Remark~\\ref{rem:antichain-equivariance},
      Proposition~\\ref{prop:leading-os-rp},
      Proposition~\\ref{prop:gamma-global-poincare}.
  - e3_orbit_selection.py    (enumeration of the 630 maximal antichains).
  - k3b_volovik_signature.py (X_mu construction, K^{mu nu} kinetic matrix).
  - k3b_c1_os_reflection_positivity.py (build_RP_matrix, random points).

Usage.
======

    python3 e3_antichain_full_sweep.py
    python3 e3_antichain_full_sweep.py --save sweep.json
    python3 e3_antichain_full_sweep.py --quick      # first 20 antichains

Optional ``--save`` writes a 630-row JSON table with one record per
antichain.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np

from _common import bootstrap_repo_root, constants_path, Result, banner, DIM_E8

ROOT = bootstrap_repo_root()
if str(Path(__file__).resolve().parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parent))

from e8sim.algebra import (  # noqa: E402
    bracket_vec_fast,
    extract_pos_roots_numpy,
    load_structure_constants_numpy,
)
from e8sim.roots import (  # noqa: E402
    e7_su2_embedding,
    is_strongly_orthogonal,
    build_compatibility_matrix,
    enumerate_antichains_of_size,
)
from e8sim.eix import (  # noqa: E402
    DIM_E8 as _DIM_E8,
    C_H_EIX,
    KAPPA_OVER_EUCLID,
    canonical_VA as build_VA,
)
from e3_orbit_selection import (  # noqa: E402
    root_set,
    m_plus_for_EIX,
)
from k3b_volovik_signature import (  # noqa: E402
    m_plus_indices_in_canonical_pos,
    build_X_mu,
    slow_mode_field_basis,
    slow_mode_kinetic_matrix,
)
from k3b_c1_os_reflection_positivity import (  # noqa: E402
    build_RP_matrix,
    random_points_positive_time,
)

assert DIM_E8 == _DIM_E8 == 248


CONSTANTS_PATH = constants_path(ROOT)

TOL_ALG = 1e-9
TOL_PSD = 1e-10
TOL_FRACT = 1e-3
N_TEST_POINTS = 30          # OS test points per antichain
RNG_BASE_SEED = 1_000_000   # offset to disambiguate from sibling RP scripts
EXPECTED_ANTICHAIN_COUNT = 630


# ----------------------------------------------------------------------
# Per-antichain verdict
# ----------------------------------------------------------------------


def per_antichain_verdict(idx: int,
                          antichain: tuple,
                          m_plus: np.ndarray,
                          root_lookup: set,
                          m_pos_idx_in_canonical: np.ndarray,
                          m_basis: np.ndarray,
                          h_basis: np.ndarray,
                          f_idx: np.ndarray,
                          f_val: np.ndarray,
                          r_sq: float,
                          n_test_points: int = N_TEST_POINTS,
                          ) -> dict:
    """Run the 8-check verdict battery on one size-4 antichain.

    Returns a dict with PASS/FAIL flags and the numerical residuals;
    aggregated across 630 calls into the sweep summary.
    """
    out: dict = {"index": idx, "antichain": list(antichain)}

    # ── C1: strong-orthogonality of all six pairs ────────────────────
    so_pairs = []
    for a in range(4):
        for b in range(a + 1, 4):
            so_pairs.append(
                is_strongly_orthogonal(m_plus[antichain[a]],
                                       m_plus[antichain[b]],
                                       root_lookup)
            )
    out["C1_strong_orth_pairs"] = int(sum(so_pairs))
    out["C1_pass"] = (sum(so_pairs) == 6)

    # ── X_μ basis and slow-mode field basis ─────────────────────────
    X = build_X_mu(m_pos_idx_in_canonical, antichain)
    E_field = slow_mode_field_basis(m_pos_idx_in_canonical, antichain)

    # ── C2: Cartan involution σ → X_μ ∈ 𝔪 ──────────────────────────
    P_m = m_basis.T @ m_basis
    P_h = h_basis.T @ h_basis
    proj_m_residual = float(np.linalg.norm(P_m @ X.T - X.T))
    proj_h_norm = float(np.linalg.norm(P_h @ X.T))
    out["C2_proj_m_residual"] = proj_m_residual
    out["C2_proj_h_norm"] = proj_h_norm
    out["C2_pass"] = (proj_m_residual < TOL_ALG and proj_h_norm < TOL_ALG)

    # ── C3: pairwise commutation [X_μ, X_ν] = 0 ─────────────────────
    max_bracket_norm = 0.0
    for mu in range(4):
        for nu in range(mu + 1, 4):
            br = bracket_vec_fast(f_idx, f_val, X[mu], X[nu])
            n = float(np.linalg.norm(br))
            if n > max_bracket_norm:
                max_bracket_norm = n
    out["C3_max_bracket_norm"] = max_bracket_norm
    out["C3_pass"] = (max_bracket_norm < TOL_ALG)

    # ── C4: restricted Killing form κ|_𝔞 = 4·𝟙 ─────────────────────
    K_a = KAPPA_OVER_EUCLID * (X @ X.T)  # (4, 4)
    K_a_diag = np.diag(K_a)
    K_a_off = K_a - np.diag(K_a_diag)
    K_a_off_max = float(np.max(np.abs(K_a_off)))
    K_a_eigs = np.sort(np.linalg.eigvalsh(K_a))
    out["C4_kappa_diag"] = K_a_diag.tolist()
    out["C4_kappa_off_max"] = K_a_off_max
    out["C4_kappa_min_eig"] = float(K_a_eigs[0])
    out["C4_pass"] = (
        K_a_off_max < TOL_ALG
        and np.allclose(K_a_diag, 4.0, atol=TOL_ALG)
        and K_a_eigs[0] > 0
    )

    # ── C5: slow-mode K^{μν} = (1/2)·𝟙 → signature (+,+,+,+) ────────
    K_munu = slow_mode_kinetic_matrix(X, E_field)
    K_eigs = np.sort(np.linalg.eigvalsh(K_munu))
    K_n_pos = int(np.sum(K_eigs > +TOL_ALG))
    K_n_neg = int(np.sum(K_eigs < -TOL_ALG))
    K_diag_mean = float(np.mean(np.diag(K_munu)))
    out["C5_K_diag_mean"] = K_diag_mean
    out["C5_K_eigs"] = K_eigs.tolist()
    out["C5_signature"] = [K_n_pos, K_n_neg, 4 - K_n_pos - K_n_neg]
    out["C5_pass"] = (K_n_pos == 4 and K_n_neg == 0
                      and abs(K_diag_mean - 0.5) < TOL_ALG)

    # ── effective mass for OS-RP ─────────────────────────────────────
    M_W_sq = C_H_EIX * r_sq  # = 1/4 · 2 = 1/2
    m_eff = float(np.sqrt(M_W_sq / K_diag_mean))
    out["m_eff"] = m_eff
    out["M_W_sq"] = M_W_sq

    # ── C6: OS reflection positivity (single time-axis = 0) ─────────
    rng = np.random.default_rng(RNG_BASE_SEED + idx)
    pts = random_points_positive_time(n_test_points, time_axis=0, rng=rng)
    M = build_RP_matrix(pts, m_eff, time_axis=0)
    sym_err = float(np.linalg.norm(M - M.T))
    eigs_M = np.linalg.eigvalsh(0.5 * (M + M.T))
    eigs_M.sort()
    M_min_eig = float(eigs_M[0])
    M_max_eig = float(eigs_M[-1])
    M_n_neg = int(np.sum(eigs_M < -TOL_PSD))
    out["C6_sym_err"] = sym_err
    out["C6_min_eig"] = M_min_eig
    out["C6_max_eig"] = M_max_eig
    out["C6_n_neg"] = M_n_neg
    out["C6_pass"] = (sym_err < TOL_ALG and M_n_neg == 0)

    # ── C7: O(4) gauge invariance of OS-RP across 4 time axes ───────
    min_eigs_per_axis = []
    n_neg_per_axis = []
    for ta in range(4):
        rng_ta = np.random.default_rng(RNG_BASE_SEED + idx + 100_000 * (ta + 1))
        pts_ta = random_points_positive_time(n_test_points, time_axis=ta,
                                              rng=rng_ta)
        M_ta = build_RP_matrix(pts_ta, m_eff, time_axis=ta)
        eigs_ta = np.linalg.eigvalsh(0.5 * (M_ta + M_ta.T))
        min_eigs_per_axis.append(float(eigs_ta.min()))
        n_neg_per_axis.append(int(np.sum(eigs_ta < -TOL_PSD)))
    out["C7_min_eigs_per_axis"] = min_eigs_per_axis
    out["C7_n_neg_per_axis"] = n_neg_per_axis
    out["C7_pass"] = all(ne == 0 for ne in n_neg_per_axis)

    # ── C8: Lorentz dispersion E² = |k|² + m² > 0, v_g < 1 ──────────
    k_samples = np.array([0.0, 0.5, 1.0, 2.0, 5.0])
    E_sq = k_samples ** 2 + m_eff ** 2
    E = np.sqrt(E_sq)
    rest_mass = float(E[0])
    v_g = k_samples[1:] / E[1:]
    out["C8_rest_mass"] = rest_mass
    out["C8_max_vg"] = float(np.max(v_g))
    out["C8_pass"] = bool(
        np.all(E_sq > 0)
        and abs(rest_mass - m_eff) < TOL_ALG
        and np.all(v_g < 1.0)
    )

    # ── overall verdict ────────────────────────────────────────────
    out["all_pass"] = all(
        out[k] for k in (
            "C1_pass", "C2_pass", "C3_pass", "C4_pass",
            "C5_pass", "C6_pass", "C7_pass", "C8_pass",
        )
    )
    # Coerce all numpy bool / numpy scalar types to JSON-native equivalents.
    for k, v in list(out.items()):
        if isinstance(v, (np.bool_,)):
            out[k] = bool(v)
        elif isinstance(v, (np.integer,)):
            out[k] = int(v)
        elif isinstance(v, (np.floating,)):
            out[k] = float(v)
    return out


# ----------------------------------------------------------------------
# Sweep + reporting
# ----------------------------------------------------------------------


def run_sweep(antichains: list,
              m_plus: np.ndarray,
              root_lookup: set,
              m_pos_idx_in_canonical: np.ndarray,
              m_basis: np.ndarray,
              h_basis: np.ndarray,
              f_idx: np.ndarray,
              f_val: np.ndarray,
              r_sq: float,
              n_test_points: int,
              progress_every: int = 50,
              ) -> list[dict]:
    rows = []
    n_total = len(antichains)
    t0 = time.time()
    for idx, ac in enumerate(antichains):
        row = per_antichain_verdict(
            idx=idx, antichain=ac,
            m_plus=m_plus, root_lookup=root_lookup,
            m_pos_idx_in_canonical=m_pos_idx_in_canonical,
            m_basis=m_basis, h_basis=h_basis,
            f_idx=f_idx, f_val=f_val,
            r_sq=r_sq, n_test_points=n_test_points,
        )
        rows.append(row)
        if (idx + 1) % progress_every == 0 or idx + 1 == n_total:
            n_pass = sum(int(r["all_pass"]) for r in rows)
            elapsed = time.time() - t0
            print(f"    {idx + 1:4d}/{n_total}  PASS so far: {n_pass}  "
                  f"({elapsed:6.1f}s, {1000 * elapsed / (idx + 1):.1f} ms/antichain)",
                  flush=True)
    return rows


def _check_distribution(rows: list[dict], key: str,
                        res: Result, label: str) -> None:
    n_total = len(rows)
    n_pass = sum(int(r[key]) for r in rows)
    res.report(
        f"{label}: PASS on all {n_total} antichains",
        n_pass == n_total,
        f"{n_pass}/{n_total} PASS"
        + (f" (FAIL on antichain indices "
           f"{[r['index'] for r in rows if not r[key]][:5]}"
           f"{'...' if (n_total - n_pass) > 5 else ''})"
           if n_pass < n_total else ""),
    )


def _check_constant(rows: list[dict], key: str, expected: float,
                    tol: float, res: Result, label: str) -> None:
    values = np.array([r[key] for r in rows], dtype=np.float64)
    max_dev = float(np.max(np.abs(values - expected)))
    std_val = float(np.std(values))
    res.report(
        f"{label}: constant across all {len(rows)} antichains "
        f"(expected {expected})",
        max_dev < tol,
        f"max |dev| = {max_dev:.3e}, std = {std_val:.3e}",
    )


def report_aggregate(rows: list[dict], res: Result,
                     enforce_full_count: bool = True) -> None:
    banner("[Aggregate] Verdict distribution across the 630-element antichain set")

    n_total = len(rows)
    print(f"    Total antichains processed: {n_total}")
    print(f"    Expected: {EXPECTED_ANTICHAIN_COUNT} "
          f"(Corollary cor:antichain-EIX; cf. e3_orbit_selection.py)")

    label = (f"Antichain count = {EXPECTED_ANTICHAIN_COUNT} "
             f"(consistency with Corollary cor:antichain-EIX)")
    if enforce_full_count:
        res.report(
            label,
            n_total == EXPECTED_ANTICHAIN_COUNT,
            f"counted {n_total}",
        )
    else:
        res.skip(
            label,
            f"sub-set sweep ({n_total} of {EXPECTED_ANTICHAIN_COUNT}); "
            f"--quick mode bypasses the full-count check",
        )

    # Per-check PASS distribution.
    _check_distribution(rows, "C1_pass", res,
                        "C1 strong-orthogonality")
    _check_distribution(rows, "C2_pass", res,
                        "C2 Cartan involution X_μ ∈ 𝔪")
    _check_distribution(rows, "C3_pass", res,
                        "C3 pairwise commutation [X_μ, X_ν] = 0")
    _check_distribution(rows, "C4_pass", res,
                        "C4 κ|_𝔞 = 4·𝟙 (positive)")
    _check_distribution(rows, "C5_pass", res,
                        "C5 K^{μν} signature (+,+,+,+)")
    _check_distribution(rows, "C6_pass", res,
                        "C6 OS reflection positivity (time-axis 0)")
    _check_distribution(rows, "C7_pass", res,
                        "C7 O(4) isotropy: OS-RP across 4 time axes")
    _check_distribution(rows, "C8_pass", res,
                        "C8 Lorentz dispersion E² > 0, v_g < 1")
    _check_distribution(rows, "all_pass", res,
                        "Overall verdict (all 8 checks)")

    # Constancy of structural numerical values.
    _check_constant(rows, "C5_K_diag_mean", 0.5, TOL_ALG, res,
                    "K^{μν}_diag = 1/2")
    _check_constant(rows, "M_W_sq", 0.5, TOL_ALG, res,
                    "M_W² = c_H · r_*² = 1/2")
    _check_constant(rows, "m_eff", 1.0, TOL_ALG, res,
                    "Effective mass m_eff = 1")

    # Min eigenvalue of OS-RP matrix: structural lower bound.
    min_eigs_C6 = np.array([r["C6_min_eig"] for r in rows])
    print(f"    C6 OS-RP min eigenvalue across {n_total} antichains:")
    print(f"      min = {float(min_eigs_C6.min()):+.3e}, "
          f"max = {float(min_eigs_C6.max()):+.3e}, "
          f"median = {float(np.median(min_eigs_C6)):+.3e}")
    res.report(
        "C6 OS-RP min eigenvalue is non-negative (within TOL_PSD) on every antichain",
        bool(min_eigs_C6.min() > -TOL_PSD),
        f"global min = {float(min_eigs_C6.min()):+.3e} > -{TOL_PSD:.0e}",
    )

    max_bracket = np.array([r["C3_max_bracket_norm"] for r in rows])
    print(f"    C3 max ‖[X_μ, X_ν]‖ across {n_total} antichains:")
    print(f"      max = {float(max_bracket.max()):.3e}, "
          f"median = {float(np.median(max_bracket)):.3e}")


# ----------------------------------------------------------------------
# Setup
# ----------------------------------------------------------------------


def _setup_globals(verbose: bool = True):
    f_idx, f_val = load_structure_constants_numpy(str(CONSTANTS_PATH))
    pos_canonical = extract_pos_roots_numpy(f_idx, f_val)
    e7_basis, su2_basis, m_basis, _ = e7_su2_embedding(pos_roots=pos_canonical)
    h_basis = np.vstack([e7_basis, su2_basis])
    V_A, r_sq = build_VA()

    all_roots = np.concatenate([pos_canonical, -pos_canonical], axis=0)
    m_plus = m_plus_for_EIX(pos_canonical)
    m_pos_idx_in_canonical = m_plus_indices_in_canonical_pos(m_plus, pos_canonical)
    rl_set = root_set(all_roots)

    if verbose:
        print(f"        |Φ| = {len(all_roots)}, |Δ(𝔪⁺)| = {len(m_plus)}")
        print(f"        h_basis = {h_basis.shape}, m_basis = {m_basis.shape}")
        print(f"        V_A in Cartan(SU(2)): r_*² = κ(V_A,V_A) = {r_sq:.4f}")

    if verbose:
        print(f"\n[setup] Building strong-orthogonality compatibility matrix "
              f"({len(m_plus)}×{len(m_plus)})...", flush=True)
    t0 = time.time()
    compat = build_compatibility_matrix(m_plus, rl_set)
    if verbose:
        print(f"        compat built in {time.time() - t0:.2f}s", flush=True)

    if verbose:
        print(f"\n[setup] Enumerating all size-4 antichains in Δ(𝔪⁺)...",
              flush=True)
    t0 = time.time()
    antichains = enumerate_antichains_of_size(compat, 4)
    if verbose:
        print(f"        enumerated {len(antichains)} antichains in "
              f"{time.time() - t0:.2f}s", flush=True)

    return {
        "f_idx": f_idx, "f_val": f_val,
        "pos_roots": pos_canonical, "all_roots": all_roots,
        "m_basis": m_basis, "h_basis": h_basis,
        "V_A": V_A, "r_sq": r_sq,
        "m_plus": m_plus, "compat": compat,
        "m_pos_idx_in_canonical": m_pos_idx_in_canonical,
        "rl_set": rl_set,
        "antichains": antichains,
    }


# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Full 630-antichain verdict sweep for EIX.",
    )
    p.add_argument(
        "--save", type=str, default=None,
        help="Path to write the 630-row JSON table (optional).",
    )
    p.add_argument(
        "--quick", action="store_true",
        help="Run on the first 20 antichains only (smoke test).",
    )
    p.add_argument(
        "--n-test-points", type=int, default=N_TEST_POINTS,
        help=f"Number of OS test points per antichain (default {N_TEST_POINTS}).",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)

    print("=" * 72)
    print("Full 630-antichain verdict sweep for EIX = E_8/(E_7 x SU(2))")
    print("Reference: sections/06-emergent-spacetime.tex, "
          "rem:antichain-equivariance")
    print("Verifies: constancy of the (alpha)/(gamma)/(epsilon) verdicts on")
    print("          the full maximal-antichain set in Delta(m_EIX^+)")
    print("=" * 72, flush=True)

    res = Result()
    t0 = time.time()

    print("\n[setup] Loading e8_constants.pt + EIX embedding...", flush=True)
    g = _setup_globals(verbose=True)

    if args.quick:
        antichains = g["antichains"][:20]
        print(f"\n[mode] --quick: running on first {len(antichains)} antichains",
              flush=True)
    else:
        antichains = g["antichains"]
        if len(antichains) != EXPECTED_ANTICHAIN_COUNT:
            print(f"\n[WARN] expected {EXPECTED_ANTICHAIN_COUNT} antichains, "
                  f"got {len(antichains)}; sweep will still run.",
                  flush=True)

    banner(f"Running verdict battery on {len(antichains)} antichains "
           f"(N_test={args.n_test_points}, base seed={RNG_BASE_SEED})")
    rows = run_sweep(
        antichains=antichains,
        m_plus=g["m_plus"], root_lookup=g["rl_set"],
        m_pos_idx_in_canonical=g["m_pos_idx_in_canonical"],
        m_basis=g["m_basis"], h_basis=g["h_basis"],
        f_idx=g["f_idx"], f_val=g["f_val"],
        r_sq=g["r_sq"], n_test_points=args.n_test_points,
    )

    report_aggregate(rows, res, enforce_full_count=not args.quick)

    if args.save:
        save_path = Path(args.save).expanduser().resolve()
        save_path.parent.mkdir(parents=True, exist_ok=True)
        meta = {
            "script": "e3_antichain_full_sweep.py",
            "expected_antichain_count": EXPECTED_ANTICHAIN_COUNT,
            "actual_antichain_count": len(rows),
            "n_test_points": args.n_test_points,
            "rng_base_seed": RNG_BASE_SEED,
            "tol_alg": TOL_ALG,
            "tol_psd": TOL_PSD,
            "checks": {
                "C1": "strong-orthogonality of all six pairs",
                "C2": "Cartan involution X_μ ∈ 𝔪",
                "C3": "pairwise commutation [X_μ, X_ν] = 0",
                "C4": "κ|_𝔞 = 4·𝟙 (positive)",
                "C5": "K^{μν} signature (+,+,+,+)",
                "C6": "OS reflection positivity (time-axis 0)",
                "C7": "O(4) isotropy: OS-RP across 4 time axes",
                "C8": "Lorentz dispersion E² > 0, v_g < 1",
            },
            "summary": {
                "passed": res.passed,
                "failed": res.failed,
                "all_pass_count": int(sum(r["all_pass"] for r in rows)),
            },
        }
        save_path.write_text(json.dumps({"meta": meta, "rows": rows}, indent=2))
        try:
            rel = save_path.relative_to(ROOT)
        except ValueError:
            rel = save_path
        print(f"\n  Sweep table written → {rel}", flush=True)

    elapsed = time.time() - t0
    print("\n" + "=" * 72)
    print(f"Summary: {res.passed} PASS / {res.failed} FAIL "
          f"({elapsed:.1f}s, {len(rows)} antichains)")
    print("=" * 72)

    if res.failed > 0:
        print("\nFailed sub-tests:")
        for marker, name, detail in res.records:
            if marker == "FAIL":
                print(f"  - {name}")
                if detail:
                    print(f"      {detail}")
        return 1

    print()
    print("Structural outcome:")
    print()
    print(f"  - All {len(rows)} antichains: 8/8 checks PASS, 0 exceptions.")
    print("  - C5 (signature), C6/C7 (OS reflection positivity), C8 (Lorentz")
    print("    dispersion) return identical numerical values up to roundoff,")
    print("    confirming antichain-independence at the operational level.")
    print("  - C3 ([X_mu, X_nu] = 0; sub-claim (epsilon) of")
    print("    Hypothesis~\\ref{hyp:4d-emergence}) holds numerically on every")
    print("    antichain, supporting Remark~\\ref{rem:antichain-equivariance}")
    print("    without invoking analytic transitivity of the residual")
    print("    E_7 x SU(2) action.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
